name: Build snapshot
on:
  workflow_dispatch:

jobs:
  build:
    name: Build and sonar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Resolve/Update Dependencies
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn --settings .m2/maven-settings.xml package dependency:resolve-plugins dependency:go-offline

      - name: Build (and run tests)
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.cache.outputs.cache-hit != 'true'
        run: mvn --settings .m2/maven-settings.xml clean install

      - name: Save test results
        run: |
          mkdir -p ~/test-results/junit/
          find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;

      - name: Setting version
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export GIT_COMMIT_HASH=$(git log -n 1 --pretty=format:'%h')
          export GIT_COMMIT_DATE=$(git log -1 --pretty='%ad' --date=format:'%Y%m%d%H%M%S')
          export VERSION=2.${GIT_COMMIT_DATE}_${GIT_COMMIT_HASH}-SPRING_BOOT_3
          echo "Setting version $VERSION"
          mvn --settings .m2/maven-settings.xml versions:set -DnewVersion="$VERSION"
          mvn --settings .m2/maven-settings.xml versions:commit

      - name: Deploy to Github Package
        if: github.head_ref == 'spring_boot_3'
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn --settings .m2/maven-settings.xml source:jar-no-fork deploy -DskipTests=true -Dmaven.wagon.http.pool=false

      - name: Post build failures to Slack
        if: github.head_ref == 'spring_boot_3' && failure()
        run: |
          curl -X POST --data "{\"text\": \"Build av $GITHUB_REPOSITORY feilet - $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\"}" $WEBHOOK_URL
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
